version: '3.2'
services:
  db:
    image: postgres
    container_name: myapp_db_container
    restart: always
    volumes:
      - /data/myapp_db_volume:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp_web_image:latest
    container_name: myapp_web_container
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  web_volume:
