version: '3.2'
services:
  db:
    image: postgres
    container_name: myapp-db-container
    restart: always
    volumes:
      - $HOME/myapp-db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp-web-container
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # volumes:
    #   - .:/myapp
    volumes:
      - type: volume
        source: myapp_web_volume
        target: /myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  myapp_web_volume:
